include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = IDFVSpooferPrefs

IDFVSpooferPrefs_FILES = IDFVSpooferPrefs.m
IDFVSpooferPrefs_FRAMEWORKS = UIKit
IDFVSpooferPrefs_PRIVATE_FRAMEWORKS = Preferences
IDFVSpooferPrefs_INSTALL_PATH = /Library/PreferenceBundles
IDFVSpooferPrefs_CFLAGS = -fobjc-arc

include $(THEOS_MAKE_PATH)/bundle.mk
